language: node_js
node_js:
  - 0.10
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - openssl aes-256-cbc -K $encrypted_9bb4a461eb9f_key -iv $encrypted_9bb4a461eb9f_iv -in deploy/id_prodA.enc -out ~/.ssh/id_prodA -d
  - openssl aes-256-cbc -K $encrypted_9bb4a461eb9f_key -iv $encrypted_9bb4a461eb9f_iv -in deploy/id_prodB.enc -out ~/.ssh/id_prodB -d

