language: node_js
node_js:
  - 0.10
before_install:
  - ls -l deploy/*
  - echo $encrypted_18b7540d5796_key
  - echo $encrypted_18b7540d5796_iv
  - openssl aes-256-cbc -K $encrypted_18b7540d5796_key -iv $encrypted_18b7540d5796_iv -in deploy/id_prodA.enc.b64 -out ~/.ssh/id_prodA -d -base64 -nopad
  - md5sum deploy/id_prodA.enc.b64
  - openssl aes-256-cbc -K $encrypted_18b7540d5796_key -iv $encrypted_18b7540d5796_iv -in deploy/id_prodB.enc -out ~/.ssh/id_prodB -d
  - head -c 30 ~/.ssh/id_prodA
  - tail -c 30 ~/.ssh/id_prodA
  - chmod 600 ~/.ssh/id_prod*
  - npm install -g grunt-cli
  - npm install -g bower
