language: node_js
node_js:
  - 0.10
before_install:
  - ls -l deploy/*
  - openssl aes-256-cbc -K $encrypted_e402cae74d66_key -iv $encrypted_e402cae74d66_iv -in deploy/id_prodA.enc -out id_prodA -d


  - openssl aes-256-cbc -K $encrypted_e402cae74d66_key -iv $encrypted_e402cae74d66_iv -in deploy/id_prodB.enc -out id_prodB -d


  - npm install -g grunt-cli
  - npm install -g bower
